"""Initial migration

Revision ID: 6bc414dba41b
Revises: 18614180db7a
Create Date: 2025-04-09 10:16:44.142147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc414dba41b'
down_revision = '18614180db7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'business', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business', type_='unique')
    # ### end Alembic commands ###